theme: jekyll-theme-minimal
title: Richmond Rockets Junior Football Club
description: A friendly North Yorkshire football club for children of all abilities
remote_theme: pages-themes/architect@v0.2.0
